# config.yaml
fusemodel: "attn"
train_dir: "./ft_datas/fold1.jsonl"
val_dir: "./ft_datas/sc_iemocap_angry_neuro.jsonl"
model_name: "/home/papa/data/papa/projects/speechllm/output/v10-20250617-105417/checkpoint-500_merge"
target_layers: [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32] 
seq_pool: "end"
select_seq: 10
feature_aggregation: "mean"
torch_dtype: "int8"
num_classes: 4
batch_size: 4
save_dir: "speechllm_cls/checkpoints/saatnet_cls_prehalf_layer_10token"
resume: null
optim_config:
  optimizer: "adamw"
  epochs: 20
  amsgrad: "False"
  base_lr: 0.00003
  lr_min: 0.000001
  betas: [0.9, 0.999]
  weight_decay: 0.05
  scheduler: "cosine"
  steps_per_epoch: 741